[package]
name = "datafusion-ethers"
version = "53.0.1"
edition = "2024"
repository = "https://github.com/kamu-data/datafusion-ethers"
description = "Ethereum RPC bridge for Apache Datafusion"
keywords = ["datafusion", "sql", "ethereum", "blockchain"]
authors = ["Kamu Data Inc. <info@kamu.dev>"]
license = "Apache-2.0"


[features]
eip712 = ["alloy-dyn-abi/eip712"]


[dependencies]
async-stream = { version = "0.3" }
async-trait = { version = "0.1" }
alloy-dyn-abi = { version = "1", default-features = false, features = ["std"] }
alloy-json-abi = { version = "1", default-features = false, features = ["std"] }
alloy-network = { version = "1", default-features = false }
alloy-primitives = { version = "1", default-features = false, features = ["std"] }
alloy-provider = { version = "1", default-features = false }
alloy-rpc-types-eth = { version = "1", default-features = false, features = [
    "std",
    "serde",
] }
alloy-transport = { version = "1", default-features = false }
datafusion = { version = "53", default-features = false, features = ["sql"] }
futures = { version = "0.3" }
serde_json = { version = "1" }
tokio = { version = "1", default-features = false }
thiserror = { version = "2" }
tracing = { version = "0.1", default-features = false }


[dev-dependencies]
alloy-contract = { version = "1", default-features = false }
alloy-node-bindings = { version = "1", default-features = false }
alloy-provider = { version = "1", default-features = false, features = [
    "ws",
    "reqwest",
    "reqwest-rustls-tls",
] }
alloy-sol-types = { version = "1", default-features = false, features = ["std"] }
datafusion = { version = "53", default-features = false, features = [
    "parquet",
] }
datafusion-functions-json = { version = "0.53", default-features = false }
indoc = { version = "2" }
pretty_assertions = { version = "1" }
test-log = { version = "0.2", features = ["trace"] }
tokio = { version = "1", default-features = false, features = [
    "macros",
    "rt-multi-thread",
] }
tracing-subscriber = { version = "0.3" }


[patch.crates-io]
# datafusion = { git = 'https://github.com/apache/datafusion.git', rev = "7bd7747" }
