[package]
name = "datafusion-ethers"
version = "38.1.1"
edition = "2021"
repository = "https://github.com/kamu-data/datafusion-ethers"
description = "Ethereum RPC bridge for Apache Datafusion"
keywords = ["datafusion", "sql", "ethereum", "blockchain"]
authors = ["Kamu Data Inc. <info@kamu.dev>"]
license = "Apache-2.0"


[dependencies]
async-stream = { version = "0.3" }
async-trait = "0.1"
alloy-core = { version = "0.7", features = [
    "std",
    "dyn-abi",
    "json-abi",
    "sol-types",
] }
datafusion = "38.0.0"
ethers = { version = "2", default-features = false, features = [
    "ws",
    "rustls",
] }
futures = { version = "0.3" }
serde_json = { version = "1" }
tokio = "1.37.0"
thiserror = "1"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
datafusion-functions-json = { version = "0.1" }
indoc = { version = "2" }
pretty_assertions = { version = "1" }
test-log = { version = "0.2", features = ["trace"] }

[patch.crates-io]
# TODO: https://github.com/datafusion-contrib/datafusion-functions-json/issues/12
datafusion-functions-json = { git = 'https://github.com/kamu-data/datafusion-functions-json.git', branch = "pin-jiter" }
