[package]
name = "datafusion-ethers"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = { version = "0.3" }
async-trait = "0.1"
alloy-core = { version = "0.7", features = [
    "std",
    "dyn-abi",
    "json-abi",
    "sol-types",
] }
datafusion = "38.0.0"
datafusion-functions-json = { version = "0.1" }
ethers = { version = "2", default-features = false, features = [
    "ws",
    "rustls",
] }
futures = { version = "0.3" }
serde_json = { version = "1" }
tokio = "1.37.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"

[dev-dependencies]
indoc = { version = "2" }
pretty_assertions = { version = "1" }
test-log = { version = "0.2", features = ["trace"] }
