[bans]
# Forbid multiple versions of same dependency (with some exceptions)
multiple-versions = "deny"
# We should slways specify version ranges
wildcards = "deny"
# We specify features explicitly to avoid bloat
workspace-default-features = "deny"
# Avoid adding dependencies to this list as this slows down compilation.
# Find another ways to avoid duplication.
skip-tree = [
    # TODO: Transition from deprecated/unmaintained ethers to alloy
    { name = "base64" },
    { name = "bitflags" },
    { name = "heck" },
    { name = "pbkdf2" },
    { name = "regex-automata" },
    { name = "regex-syntax" },
    { name = "ring" },
    { name = "send_wrapper" },
    { name = "toml_edit" },
    { name = "uuid" },
    { name = "winnow" },
]
deny = [{ name = "openssl" }]


[licenses]
allow = [
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "ISC",
    "MIT",
    "MPL-2.0",
    "0BSD",
    "OpenSSL",
    "Unlicense",
    "Zlib",
]
# copyleft = "deny"
private = { ignore = true }

[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-ident"


[[licenses.clarify]]
name = "ring"
expression = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]


[sources]
unknown-git = "deny"
unknown-registry = "deny"
allow-org = { github = ["kamu-data"] }


[advisories]
yanked = "deny"
ignore = []
